services:
  emenu_db:
    hostname: emenu_db
    container_name: emenu_db
    image: mongo
    expose:
      - 27017
    #ports:
    #  - 27017:27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${EMENU_API_DB_PWD}
      - MONGO_INITDB_ROOT_USERNAME=${EMENU_API_DB_USER}
    volumes:
      - emenu_db:/data/db
      - emenu_db_config_db:/data/configdb
  emenu_api:
    hostname: emenu_api
    container_name: emenu_api
    restart: unless-stopped
    image: mute/emenu-api:latest
    expose:
     - 80
    environment:
      - VIRTUAL_HOST=${EMENU_API_DOMAIN}
      - LETSENCRYPT_HOST=${EMENU_API_DOMAIN}
      - MongoDbConfig__ConnectionString=mongodb://${EMENU_API_DB_USER}:${EMENU_API_DB_PWD}@emenu_db:27017/?authSource=admin

volumes:
 emenu_db: null
 emenu_db_config_db: null

networks:
  default:
    external:
      name: ${DOCKER_NETWORK}
