services:
  mongo-setup:
    container_name: mongo-setup
    image: mongo
    restart: on-failure
    networks:
      default:
    volumes:
      - ./scripts:/etc/
    entrypoint: [ "/etc/setup.sh" ]
    depends_on:
      - mongo1
      - mongo2
      - mongo3
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo
    expose:
      - 27017
    ports:
      - 27017:27017
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0",
        "--journal",
        "--dbpath",
        "/data/db",
        "--port",
        "27017"
      ]
    volumes:
      - mongo1_db:/data/db
      - mongo1_config_db:/data/configdb
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo
    expose:
      - 27018
    ports:
      - 27018:27018
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0",
        "--journal",
        "--dbpath",
        "/data/db",
        "--port",
        "27018"
      ]
    volumes:
      - mongo2_db:/data/db
      - mongo2_config_db:/data/configdb
  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo
    expose:
      - 27019
    ports:
      - 27019:27019
    restart: always
    entrypoint:
      [
        "/usr/bin/mongod",
        "--bind_ip_all",
        "--replSet",
        "rs0",
        "--journal",
        "--dbpath",
        "/data/db",
        "--port",
        "27019"
      ]
    volumes:
      - mongo3_db:/data/db
      - mongo3_config_db:/data/configdb

volumes:
 mongo1_db: null
 mongo2_db: null
 mongo3_db: null
 mongo1_config_db: null
 mongo2_config_db: null
 mongo3_config_db: null
